apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: medrecapi
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: medrecapi
        version: v1
    spec:
      containers:
      - name: medrecapi
        image: lmukadam/acmeblog:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: medrecapi
  labels:
    app: medrecapi
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: medrecapi
